# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-25 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contributions',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
